services:
  - docker

script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_USERPASS"
  - git clone -b master https://github.com/compdatasci/dockerfiles.git dockerfiles
  - docker build --tag compdatasci/octave-jupyter dockerfiles/octave-jupyter && docker push compdatasci/octave-jupyter && curl -X POST https://registry.hub.docker.com/u/compdatasci/octave-jupyter/trigger/$TOKEN_OCTAVE/ && touch success
  - docker images
